function f=Gfun(Lambda,t,x)
f=(Lambda./b(t,x)+2*(1-Lambda./b(t,x))).*...
    ((gtt(t,x).*kappa_t(t,x)+grt(t,x).*kappa_r(t,x)).*...
    xi_t(t,x)+(grr(t,x).*kappa_r(t,x)+grt(t,x).*kappa_t(t,x)).*xi_r(t,x));
end