function f=Y1(Lambda,epsilon,t,x,tau,p)  % the integrand of Yp
f=Gfun(Lambda,t,x).*qprofile(x)/...
       sqrt(2*epsilon)./tau./b(t,x)./...
        sqrt(1-Lambda./b(t,x)) .*...
        exponent(Lambda,epsilon,t,x,tau,p);
end
